name: Block direct commits to master

on:
  push:
    branches:
      - master

jobs:
  block-direct-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check for direct commits to master
        run: |
          # Get the commit history
          git fetch origin master
          # Get the last merge commit on master
          last_merge_commit=$(git log --merges -n 1 --pretty=format:"%H")
          # Get the last commit on master
          last_commit=$(git rev-parse HEAD)

          # If the last commit is not a merge commit, fail the workflow
          if [ "$last_commit" != "$last_merge_commit" ]; then
            echo "Direct commits to master are not allowed."
            exit 1
          fi
